feat: use sauce connect launcher for open and close connection
gemini-testing/hermione-sauce-connect pull request #2
Opened 2019-08-22 08:39 UTC by TheNech

Реализована функциональность плагина по открытию и закрытию подключения к Sauce Connect Proxy сразу после запуска и остановки интеграционного тестирования Гермионой.

2019-08-22 13:45 UTC, CatWithApple requested changes

2019-08-22 13:45 UTC, CatWithApple commented on README.md
> +Use `hermione_sauce_` prefix for the environment variables and `--hermione_sauce-` for the cli options.
если я ничего не путаю, то переменная окружения для accessKey будет `hermione_sauce_access_key`, а cli опция `--hermione-sauce-access-key`. т.е. сказать про префикс не достаточно.

2019-08-22 13:45 UTC, CatWithApple commented on README.md
> +* **accessKey** (required) `String` - Sauce Labs access key.
я бы предостерёг от коммита поля accessKey конфигурации в публичные репозитории

2019-08-22 13:45 UTC, CatWithApple commented on README.md
> +Use `hermione_sauce_` prefix for the environment variables and `--hermione_sauce-` for the cli options.
а почему префикс `hermione_sauce_`, а не `hermione_sauce_connect_`?

2019-08-22 13:45 UTC, CatWithApple commented on lib/config.js
> +const option = configParser.option;
const {root, section, option} = require('gemini-configparser');

2019-08-22 13:45 UTC, CatWithApple commented on lib/config.js
> +const CLI_PREFIX = '--hermione_sauce-';
в cli опции стоит заменить `_` на `-`

2019-08-22 13:45 UTC, CatWithApple commented on lib/sauce.js
> +        this._sauceConnectProcess;
не понятно, зачем сейчас эта строчка.
можешь присвоить null и будет нормально.

2019-08-22 13:45 UTC, CatWithApple commented on lib/sauce.js
> +        const sauceOptions = {
зачем создавать sauceOptions? 
зачем нужен отдельный метод _sauceConnectStart? стоит занеси его тело в метода start

2019-08-22 13:45 UTC, CatWithApple commented on lib/sauce.js
> +        this._sauceConnectStop();
опять же. не нужен отдельный метод _sauceConnectStop
и похоже, ты забыл return

2019-08-22 13:45 UTC, CatWithApple commented on lib/sauce.js
> +            return new Promise((resolve) => {
нет причины, по которой вторая ветка не должна возвращать Promise.

2019-08-22 13:45 UTC, CatWithApple commented on lib/sauce.js
> +            sauceConnectLauncher(opts, function(err, sauceConnectProcess) {
можно использовать promisify
https://nodejs.org/api/util.html#util_util_promisify_original

2019-08-22 13:45 UTC, CatWithApple commented on test/unit/lib/sauce.js
> +    // const sandbox = sinon.sandbox.create();
это что?

2019-08-22 13:45 UTC, CatWithApple commented on test/unit/lib/sauce.js
> +                'sauce-connect-launcher': sauceConnectLauncher
вроде это можно вынести в beforeEach

2019-08-22 13:45 UTC, CatWithApple commented on README.md
> +Use `hermione_sauce_` prefix for the environment variables and `--hermione_sauce-` for the cli options.
в cli oпции не стоит использовать `_`

2019-08-22 13:47 UTC, CatWithApple commented on scripts/preinstall.js
> +process.env['SAUCE_CONNECT_DOWNLOAD_ON_INSTALL'] = true;
🧐

2019-08-22 13:52 UTC, TheNech commented on README.md
> +Use `hermione_sauce_` prefix for the environment variables and `--hermione_sauce-` for the cli options.
> если я ничего не путаю, то переменная окружения для accessKey будет `hermione_sauce_access_key`, а cli опция `--hermione-sauce-access-key`. т.е. сказать про префикс не достаточно.

Согласен, стоит добавить в пример.

2019-08-22 13:54 UTC, TheNech commented on README.md
> +Use `hermione_sauce_` prefix for the environment variables and `--hermione_sauce-` for the cli options.
> а почему префикс `hermione_sauce_`, а не `hermione_sauce_connect_`?

Посчитал, что немного короче префикс будет удобней

2019-08-22 13:55 UTC, TheNech commented on README.md
> +* **accessKey** (required) `String` - Sauce Labs access key.
Предупреждающим сообщением и советом использовать переменные окружения?

2019-08-22 13:56 UTC, j0tunn commented on lib/config.js
> +const CLI_PREFIX = '--hermione_sauce-';
в cli опции вообще не нужно писать `hermione`. Это и так опции для запуска `hermione`

2019-08-22 13:57 UTC, TheNech commented on test/unit/lib/sauce.js
> +    // const sandbox = sinon.sandbox.create();
Это не пригодилось и забыл убрать.

2019-08-22 13:58 UTC, TheNech commented on scripts/preinstall.js
> +process.env['SAUCE_CONNECT_DOWNLOAD_ON_INSTALL'] = true;
Пакет, который сейчас используется, не скачивает Sauce Connect сразу, если не указать переменную окружения. Я отправил PR в репозиторий пакета.

2019-08-22 14:00 UTC, CatWithApple commented on README.md
> +* **accessKey** (required) `String` - Sauce Labs access key.
типа того.
и на всякий случай уточню, что я говорю только про документацию.

2019-08-22 14:01 UTC, TheNech commented on lib/config.js
> +const CLI_PREFIX = '--hermione_sauce-';
То есть просто `sauce_connect_`?

2019-08-22 14:01 UTC, CatWithApple commented on scripts/preinstall.js
> +process.env['SAUCE_CONNECT_DOWNLOAD_ON_INSTALL'] = true;
я понимаю, но все равно напрягает )
думаю, стоит оставить комментарий в коде

2019-08-22 14:03 UTC, CatWithApple commented on lib/config.js
> +const CLI_PREFIX = '--hermione_sauce-';
const CLI_PREFIX = '--sauce-connect-';

2019-08-22 15:02 UTC, TheNech commented on lib/sauce.js
> +        const sauceOptions = {
> зачем создавать sauceOptions?
Кажется, опции из отдельной переменной лучше читаются

2019-08-22 15:08 UTC, CatWithApple commented on lib/sauce.js
> +        const sauceOptions = {
можно сделать так
```
const {username, accessKey} = this._config;

this._sauceConnectProcess = await this._sauceConnectStart({username, accessKey})
```

2019-08-22 15:09 UTC, CatWithApple commented on lib/sauce.js
> +        const sauceOptions = {
если не брать в рассчёт, что отдельный метод _sauceConnectStart вообще не нужен

2019-08-23 14:41 UTC, TheNech commented on test/unit/lib/sauce.js
> +                'sauce-connect-launcher': sauceConnectLauncher
Не получается, так как в разных тестах `sauceConnectLauncher` выполняет разные действия: `yields()`, `rejects()`.

2019-08-23 15:53 UTC, CatWithApple approved these changes
в целом ок

2019-08-23 15:53 UTC, CatWithApple commented on README.md
> +**:warning: Do not commint your Sauce Labs credentials. Use CLI options or environment variables.**
commint - ошибка

2019-08-23 15:53 UTC, CatWithApple commented on README.md
> +**:warning: Do not commint your Sauce Labs credentials. Use CLI options or environment variables.**
> Use CLI options or environment variables

я так подумал, давай это предложение всё-таки уберём. credentials могут быть закоммичены и для CLI опции и для переменной окружения.

2019-08-23 15:53 UTC, CatWithApple commented on lib/config.js
> +const ENV_PREFIX = 'sauce_connect_';
а вот для переменной окружения не очевидно, что она может быть использована только в hermione плагине. 
`const ENV_PREFIX = 'hermione_sauce_connect_';`

2019-08-23 15:53 UTC, CatWithApple commented on lib/sauce.js
> +        const sauceConnect = util.promisify(sauceConnectLauncher);
обычно util.promisify применяется где-то в глобал скоупе. чтобы разгрузить логику методов.

2019-08-23 15:53 UTC, CatWithApple commented on lib/sauce.js
> +        this._sauceConnectProcess = await sauceConnect({username, accessKey, logger: console.log, verbose: true});
думаю, имеет смысл verbose сделать опцией плагина, которая по умолчанию выключена.

2019-08-26 07:42 UTC, TheNech commented
/fixed @DudaGod

2019-08-26 10:43 UTC, CatWithApple commented on lib/config.js
> +            validate: assertBoolean('enabled')
не поправил после copy-paste

2019-08-26 10:59 UTC, TheNech commented on lib/config.js
> +            validate: assertBoolean('enabled')
Исправил через force-pushed

2019-08-26 12:34 UTC, DudaGod requested changes

2019-08-26 12:34 UTC, DudaGod commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) to launche an instance of [Sauce Connect Proxy](https://saucelabs.com/docs/sauce-connect) when integration testing started.
launchE -> launch

2019-08-26 12:34 UTC, DudaGod commented on README.md
> +* **accessKey** (required) `String` - Sauce Labs access key.
тут ничего в доку про warning не ндобавили

2019-08-26 12:34 UTC, DudaGod commented on index.js
> +    if (!_.isObject(opts) || opts.enabled === false) {
Тут нет кейса когда `opts` пустой будет, так как у тебя в конфиге есть `required` поля

2019-08-26 12:34 UTC, DudaGod commented on lib/config.js
> +            parseCli: String,
а зачем тут и ниже писать `String`? В каком случае переменная окружения или cli опция может быть не строкой?

2019-08-26 12:34 UTC, DudaGod commented on lib/config.js
> +    const argv = process.argv;
Как вариант:
```
const {env, argv} = process;
```

2019-08-26 12:34 UTC, DudaGod commented on index.js
> +'use strict';
я бы этот файл в `lib/index.js` унес (не принципиально)

2019-08-26 12:34 UTC, DudaGod commented on scripts/postinstall.js
> +// was need to download Sauce Connect after install sauce-connect-launcher
Я бы просто описал, что очищаем переменные окружения выставленные в `preinstall` хуке

2019-08-26 12:34 UTC, DudaGod commented on test/mocha.opts
> +--reporter spec
кажется это отчет по умолчанию. Зачем его задавать?

2019-08-26 12:34 UTC, DudaGod commented on test/mocha.opts
> +--timeout 200
А для чего ты явно время ограничиваешь?

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    const sandbox = sinon.sandbox.create();
Вместо `sinon.sandbox.create` уже можно юзать просто `sinon.stub`. Кажется начиная с версии 7.0.0. Почитай в доке sinon-а.

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        sandbox.spy(Sauce, 'create');
Я бы так написал:
```
sinon.stub(Sauce, 'create').returns(Object.create(Sauce.prototype));
```

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    it('should not create an instance if passed config is string', () => {
этот тест не нужен

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    const mkHermione_ = (config) => stubTool(config, events);
тебе тут нужно по умолчанию выставлять необходимый конфиг.

```
function mkHermione_(config = {}) {
    config = _.defaults(config, {
        a: 1,
        b: 2
    });

    return stubTool(config, events);
}
```

В итоге от функции `getDefaultOpts ` можно избавиться. И почему `events` нельзя прокидывать?

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        const hermione = mkHermione_(initialOpts);
В итоге тут можно будет написать вот так:
```js
const hermione = mkHermione_({enabled: false});
```

То есть я одной строкой описал, то что у тебя описано в трех. А смысл тот же.

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        assert.isUndefined(initSauceConnect(hermione, 'config'));
я бы тут разделил `act` от `assert`

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    ['username', 'accessKey'].forEach((option) => {
зачем ты такие тесты пишешь? Это уже проверено в пакете `configparser`

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        sandbox.stub(Sauce.prototype, 'start');
у тебя метод `start` асинхронный и должен возвращать промис

2019-08-26 12:34 UTC, DudaGod commented on lib/sauce.js
> +        return this._sauceConnectProcess.close();
судя по коду метод `close` тоже асинхронный. Проверь пожалуйста.

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        assert.calledWith(Sauce.create, opts);
есть же `calledOnceWith`

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    it('should start connection process', () => {
эта функция должна быть асинхронной

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +        hermione.emitAndWait(events.RUNNER_START);
тут нужно дожидаться завершения

2019-08-26 12:34 UTC, DudaGod commented on test/unit/index.js
> +    it('should stop connection process', () => {
эта тоже должная быть асинхронной

2019-08-26 12:34 UTC, DudaGod commented on test/unit/lib/config.js
> +        it('should validate if passed value is string', () => {
тут нужно писать, что будет брошена ошибка если передать не `boolean`

2019-08-26 12:34 UTC, DudaGod commented on test/unit/lib/sauce.js
> +    const getDefaultOpts = () => ({
этот метод излишний. Выше писал как можно переписать.

2019-08-26 12:34 UTC, DudaGod commented on test/unit/lib/sauce.js
> +                'sauce-connect-launcher': sauceConnectLauncher
так указывай что он будет делать явно в каждом тесте. Это нужно унести в `beforeEach`

2019-08-26 12:34 UTC, DudaGod commented on test/unit/lib/sauce.js
> +            const sauceConnectLauncher = sinon.stub().yields(null, {
не нужно стабать в каждом тесте

2019-08-26 12:34 UTC, DudaGod commented on test/unit/lib/sauce.js
> +            await sauce.start();
а зачем этот вызов?

2019-08-26 13:40 UTC, TheNech commented on test/mocha.opts
> +--timeout 200
Не помню, где увидел эту опцию. Посчитал хорошей практикой

2019-08-26 13:47 UTC, TheNech commented on lib/sauce.js
> +        return this._sauceConnectProcess.close();
Да, асинхронный. Так сделано, чтобы не нужно было ждать закрытия соединения после выполнения тестов.

2019-08-26 13:59 UTC, TheNech commented on test/unit/index.js
> +    const mkHermione_ = (config) => stubTool(config, events);
Согласен, так удобней, чем каждый раз `getDefaultOpts` вызывать.
Я посчитал, что `events` не потребуется менять. Сделаю возможность проброса

2019-08-26 14:25 UTC, TheNech commented on test/unit/index.js
> +        assert.calledWith(Sauce.create, opts);
Его же нет по умолчанию.

Я видел такой код, чтобы добавить `calledOnceWith`:
```
global.assert.calledOnceWith = (...args) => {
    assert.calledOnce(args[0]);
    assert.calledWith(...args);
};
```

2019-08-26 14:53 UTC, TheNech commented on test/unit/index.js
> +        assert.calledWith(Sauce.create, opts);
Из-за `calledOnceWith` придется оставить `getDefaultOps()`

2019-08-26 15:10 UTC, TheNech commented on test/unit/lib/sauce.js
> +            await sauce.start();
В конструкторе должен быть записан `_sauceConnectProcess`, чтобы в `stop()` вызвать его метод `close`

2019-08-26 15:21 UTC, TheNech commented
@DudaGod /fixed

2019-08-27 14:42 UTC, DudaGod requested changes
Уже близко

2019-08-27 14:42 UTC, DudaGod commented on README.md
> +**:warning: Do not commit your Sauce Labs credentials.**
а почему этот warning тут висит? А не рядом опцией `accessKey`. Тут же речь только про него идет

2019-08-27 14:42 UTC, DudaGod commented on README.md
>              // configuration
так а чего пример конфигурации не вставить? Типа `enabled: true` и `username` например

2019-08-27 14:42 UTC, DudaGod commented on index.js
> +    if (opts.enabled === false) {
зачем явно на `false` проверять? У тебя же оно итак только `boolean` может быть. Давай просто через `!` проверим

2019-08-27 14:42 UTC, DudaGod commented on lib/sauce.js
> +        return this._sauceConnectProcess.close();
Давай все таки дожидается, иначе он может до конца не закрыться и висеть в памяти.

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +    const getDefaultOpts = () => ({
давай вместо того, чтобы описывать все поля плагина тут будем просто стабать `parseConfig`, который будет нам что-то возвращать. А затем проверять, что `Sauce.connect` был вызван с этим "чем-то"

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +const sauceConnect = require('index');
я бы эту переменную назвал просто `plugin`

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +    const initSauceConnect = (hermione, opts = {}) => {
и кстати почему у тебя этот метод называется `initSauceConnect`? Почему не `runPlugin` какой нибудь или `initPlugin`?

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +        assert.calledOnceWith(Sauce.create, getDefaultOpts());
тут нужно проверять, что в `Sauce.create` передался `config` который вернул твой стаб `parseConfig` при вызове

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +        hermione.emitAndWait(await defaultEvents.RUNNER_START);
что тут внутри вызова делает `await`?

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +    const defaultEvents = {
я бы эти эвенты расписал внутри `stubTool`.
А при вызове `emitAndWait` писал бы так:
```js
hermione.emitAndWait(hermione.events.RUNNER_START)
```

2019-08-27 14:42 UTC, DudaGod commented on test/unit/index.js
> +        assert.calledOnce(await Sauce.prototype.stop);
а тут зачем `await`? Тебе же его нужно указать строчкой выше

2019-08-27 14:42 UTC, DudaGod commented on test/unit/lib/config.js
> +    describe('"username" option', () => {
`username` и `accessKey` можно объединить в один `forEach`. У них же тест одинаковые

2019-08-27 14:42 UTC, DudaGod commented on test/unit/lib/config.js
> +    describe('"verbose" option', () => {
`enabled` и `verbose` тоже можно объедить в один `forEach`

2019-08-27 14:42 UTC, DudaGod commented on test/unit/lib/sauce.js
> +            accessKey: 'some-key'
обычно пишут `default-...`, чтобы сразу было понятно, что это дефолтное значение

2019-08-27 14:42 UTC, DudaGod commented on test/unit/lib/sauce.js
> +    describe('.start', () => {
почему у тебя именно такой нейминг describe-ов?

2019-08-27 14:42 UTC, DudaGod commented on test/unit/lib/sauce.js
> +            sauce.stop();
это же тоже асинхронный метод

2019-08-27 14:47 UTC, TheNech commented on README.md
> +**:warning: Do not commit your Sauce Labs credentials.**
Потому что раньше здесь еще был совет по использованию переменных окружения и CLI.
Ок, подниму выше.

2019-08-27 14:49 UTC, TheNech commented on test/unit/lib/config.js
> +    describe('"verbose" option', () => {
Они разные по умолчанию: `enabled: true`, а `verbose: false`

2019-08-27 14:50 UTC, TheNech commented on test/unit/lib/sauce.js
> +    describe('.start', () => {
Методы объекта. Лучше без точки?

2019-08-27 14:51 UTC, TheNech commented on test/unit/index.js
> +    const initSauceConnect = (hermione, opts = {}) => {
Так как плагин подключен в переменную `sauceConnect `. Переименую выше и здесь

2019-08-27 16:01 UTC, TheNech commented on index.js
> +    if (opts.enabled === false) {
Потому что если не указать опцию `enabled` в конфиге плагина, то она приведется к `false` и плагин не отработает

2019-08-27 18:52 UTC, TheNech commented
@DudaGod /fixed

2019-08-28 14:50 UTC, DudaGod approved these changes
в остальном /ok

2019-08-28 14:50 UTC, DudaGod commented on test/unit/index.js
> +        initPlugin(hermione, {enabled: false});
почему бы просто не передать внутрь `initPlugin` первым аргументом `mkHermione_()`? Ты же переменную `hermione` в этом тесте вообще никак не используешь

2019-08-28 14:50 UTC, DudaGod commented on test/unit/index.js
> +        initPlugin(hermione, {enabled: false});
И зачем нам второй аргумент передавать? Если у нас все зависит от того, что `parseConfig` вернет. То есть можно в `beforeEach`, что `parseConfig` всегда возваращет `{enabled: true}`. А в необходимых тестах переопределять `returns`

2019-08-28 14:50 UTC, DudaGod commented on test/unit/index.js
> +        assert.calledOnceWith(Sauce.create, {enabled: true, foo: 'bar'});
тест должен быть самодостаточным. В данном случае мне непонятно откуда в этом тесте появилось `foo: bar`.

Т.е. в этом тесте ты должен был явно указать:
```
parseConfig.returns({enabled: true, foo: 'bar'});
```

2019-08-28 14:50 UTC, DudaGod commented on test/unit/index.js
> +    const initPlugin = (hermione, opts = {enabled: true}) => {
выглядит так, что здесь нужно переопределять, то что возвращает `parseConfig` ->`parseConfig.returns(opts)`

В итоге можно будет в `it`-ах просто писать:
```
initPlugin(mkHermione_(), {enabled: true, foo: bar});
```

и не указывать, что возвращает `parseConfig`

2019-08-28 14:50 UTC, DudaGod commented on test/unit/index.js
> +        hermione.emitAndWait(hermione.events.RUNNER_END);
почему тут `await`-а нет?

2019-08-28 14:50 UTC, DudaGod commented on test/unit/lib/sauce.js
> +    describe('.start', () => {
я обычно просто пишу -> '"start"', но можешь и такой оставить

2019-08-29 07:27 UTC, merged